package gofins

import "fmt"

// endCodeText 完整的 FINS end code 表（Omron W342-E1-15 第 155-161 页，转写自 l1va/gofins）。
// 表里没有的码由 EndCodeToString 带上 16 进制返回——旧实现只覆盖约三分之一，
// 其余一律回 "Unknown end code"，连码值都丢了。
var endCodeText = map[uint16]string{
	0x0000: "normal completion",
	0x0001: "normal completion; service was interrupted",
	0x0101: "local node error; local node not in network",
	0x0102: "local node error; token timeout",
	0x0103: "local node error; retries failed",
	0x0104: "local node error; too many send frames",
	0x0105: "local node error; node address range error",
	0x0106: "local node error; node address range duplication",
	0x0201: "destination node error; destination node not in network",
	0x0202: "destination node error; unit missing",
	0x0203: "destination node error; third node missing",
	0x0204: "destination node error; destination node busy",
	0x0205: "destination node error; response timeout",
	0x0301: "controller error; communication controller error",
	0x0302: "controller error; CPU unit error",
	0x0303: "controller error; controller error",
	0x0304: "controller error; unit number error",
	0x0401: "service unsupported; undefined command",
	0x0402: "service unsupported; not supported by model version",
	0x0501: "routing table error; destination address setting error",
	0x0502: "routing table error; no routing tables",
	0x0503: "routing table error; routing table error",
	0x0504: "routing table error; too many relays",
	0x1001: "command format error; command too long",
	0x1002: "command format error; command too short",
	0x1003: "command format error; elements/data don't match",
	0x1004: "command format error; command format error",
	0x1005: "command format error; header error",
	0x1101: "parameter error; classification missing",
	0x1102: "parameter error; access size error",
	0x1103: "parameter error; address range error",
	0x1104: "parameter error; address range exceeded",
	0x1106: "parameter error; program missing",
	0x1109: "parameter error; relational error",
	0x110A: "parameter error; duplicate data access",
	0x110B: "parameter error; response too big",
	0x110C: "parameter error",
	0x2002: "read not possible; protected",
	0x2003: "read not possible; table missing",
	0x2004: "read not possible; data missing",
	0x2005: "read not possible; program missing",
	0x2006: "read not possible; file missing",
	0x2007: "read not possible; data mismatch",
	0x2101: "write not possible; read only",
	0x2102: "write not possible; write protected",
	0x2103: "write not possible; cannot register",
	0x2105: "write not possible; program missing",
	0x2106: "write not possible; file missing",
	0x2107: "write not possible; file name already exists",
	0x2108: "write not possible; cannot change",
	0x2201: "not executeable in current mode during execution",
	0x2202: "not executeable in current mode while running",
	0x2203: "not executeable in current mode; PLC is in PROGRAM mode",
	0x2204: "not executeable in current mode; PLC is in DEBUG mode",
	0x2205: "not executeable in current mode; PLC is in MONITOR mode",
	0x2206: "not executeable in current mode; PLC is in RUN mode",
	0x2207: "not executeable in current mode; specified node is not polling node",
	0x2208: "not executeable in current mode; step cannot be executed",
	0x2301: "no such device; file device missing",
	0x2302: "no such device; memory missing",
	0x2303: "no such device; clock missing",
	0x2401: "cannot start/stop; table missing",
	0x2502: "unit error; memory error",
	0x2503: "unit error; IO error",
	0x2504: "unit error; too many IO points",
	0x2505: "unit error; CPU bus error",
	0x2506: "unit error; IO duplication",
	0x2507: "unit error; IO bus error",
	0x2509: "unit error; SYSMAC BUS/2 error",
	0x250A: "unit error; CPU bus unit error",
	0x250D: "unit error; SYSMAC bus number duplication",
	0x250F: "unit error; memory status error",
	0x2510: "unit error; SYSMAC bus terminator missing",
	0x2601: "command error; no protection",
	0x2602: "command error; incorrect password",
	0x2604: "command error; protected",
	0x2605: "command error; service already executing",
	0x2606: "command error; service stopped",
	0x2607: "command error; no execution right",
	0x2608: "command error; settings not complete",
	0x2609: "command error; necessary items not set",
	0x260A: "command error; number already defined",
	0x260B: "command error; error will not clear",
	0x3001: "access write error; no access right",
	0x4001: "abort; service aborted",
}

// EndCodeToString returns a human-readable description of the end code.
func EndCodeToString(code uint16) string {
	if s, ok := endCodeText[code]; ok {
		return s
	}
	return fmt.Sprintf("Unknown end code (0x%04X)", code)
}
